### ISSUE TITLE
no subscription button/link 

### ISSUE THREAD

**Issue by skeydan** [rstudio/tensorflow-blog#1]
I don't see a button/link I could click to subscribe (on Firefox)

```
<div id="subscribe-caption" style="line-height: 1.2; margin-bottom: 2px; width: 377px; font-size: 15px;">
Enjoy this blog? Get notified of new posts by email:
</div>
```

**Comment by jjallaire** [comment]
The subscribe button comes in on a delay. Do you see it after waiting for a few seconds?

If not, maybe try loading the page with the Firefox console open and letting me know if there are any JavaScript errors reported.

**Comment by skeydan** [comment]
Seems to be because of tracking protection (and consequently, an undefined variable)

![screenshot from 2018-07-15 17-57-22](https://user-images.githubusercontent.com/469371/42735651-93b86484-8858-11e8-986d-86a36f86791a.png)

**Comment by jjallaire** [comment]
Okay, I don't think there is much we can do about this one (I'll mention it Bill though to see if we can create subscription snippets that don't have this issue).

**Comment by skeydan** [comment]
just noticed, works for me now!
