### ISSUE TITLE
broken link in tensorflow-blog/_posts/2018-06-25-sunspots-lstm/

### ISSUE THREAD

**Issue by hansthompson** [rstudio/tensorflow-blog#24]
On line 194, the link to "Time Series Analysis Example" should point to

https://tidymodels.github.io/rsample/articles/Applications/Time_Series.html 

instead of 

https://topepo.github.io/rsample/articles/Applications/Time_Series.html

as it is currently broken and I think this is new link. Thanks for this EXCELLENT post and keep up the good good good good work. 💯

**Comment by skeydan** [comment]
Hi,

thanks a lot for pointing this out!!
Will be fixed in 

https://github.com/rstudio/tensorflow-blog/pull/27
