### ISSUE TITLE
Narative differs from code on 2018-06-25-sunspots-lstm for training, testing, and skip periods. 

### ISSUE THREAD

**Issue by hansthompson** [rstudio/tensorflow-blog#25]
The narative says a 

training period of 50 years, a testing period of 10 years, and a skip span of 20 years but the code has a 
training period of 100 years, a testing period of 50 years, and skip span of 22 years. 

Again, thanks for what you do. 👍

**Comment by skeydan** [comment]
Again, thank _you_!

Fix in https://github.com/rstudio/tensorflow-blog/pull/27
