### ISSUE TITLE
post for RStudio/tensorflow blog

### ISSUE THREAD

**Issue by henry090** [rstudio/tensorflow-blog#52]
Hi, I have just done writing a post for tensorflow blog (Loading Bert model from R).
Could you review it, please?
https://github.com/henry090/BERT-from-R

**Comment by skeydan** [comment]
Hi,

thanks for the contribution, that looks like useful information for our readers!

Can you fork the repo, create a branch for your post and then, create a PR?
I can then directly comment in the PR.

I would also recommend having all output static (setting eval = FALSE everywhere), which is the safest option for redeployments.

Thanks!

**Comment by henry090** [comment]
Thank you, I create PR and just kept eval=T where I show a figure from the source. Is that OK?

**Comment by henry090** [comment]
I am a Data Scientist at AccessBank Azerbaijan who currently pursuing a Ph.D. in economics from the Baku State University, Azerbaijan.

Thank you, Sigrid!

**Comment by henry090** [comment]
Thank you so much for your time and HELP, Sigrid! :-)
