### ISSUE TITLE
  could not find function "%<-%

### ISSUE THREAD

**Issue by MarcosGrzeca** [rstudio/tensorflow-blog#56]
c(indices, target, segments) %<-% list(list(),list(),list())
Error in c(indices, target, segments) %<-% list(list(), list(), list()) :
  could not find function "%<-%"

Can you help me, please?

**Comment by dfalbel** [comment]
This function comes from the package [`zeallot`](https://github.com/r-lib/zeallot). Just install `install.packages("zeallot")` and then `library(zeallot)`.
